### ISSUE TITLE
Could we enable the Save Changes button only when there are changes needing saving

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#305]
Might be a nice visual cue. What do you think @kellychoffman  ?

![disable-save-changes-until-there-are-changes-needing-saving](https://cloud.githubusercontent.com/assets/1595739/15086581/a6f54212-1396-11e6-957c-c408b4ba4c78.gif)

**Comment by kellychoffman** [comment]
I think an always active save button is good to have. We've all been felt the fire of losing unsaved 'work' before. A smart designer I work with once said, "A placebo save feels good." 

I have no problem with keeping it always active, especially if there's a warning when you _have_ done something and you go to leave the page. That, we don't have. 

I vote in favor of closing this issue and opening a new one for the alert.

PS. Nice Boxy McBoxface. Was this a result of a contest I was unaware of?

**Comment by kellychoffman** [comment]
Reopening because I think we should always be able to save for the reasons in the comment above. Right now, I'm seeing a disabled save:

<img width="727" alt="screen shot 2016-05-27 at 6 15 17 pm" src="https://cloud.githubusercontent.com/assets/5835847/15623845/3ffffa78-2437-11e6-8e2c-f298ecab637e.png">
