### ISSUE TITLE
In Edit Order, tell the merchant what box(es) the server picked for the item(s) in an order

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#312]
I created two packages in my USPS instance:

<img width="696" alt="screen shot 2016-05-06 at 4 12 11 pm" src="https://cloud.githubusercontent.com/assets/1595739/15088184/55e41b5a-13a5-11e6-9f61-0809dcb7c456.png">

I then bought a single 2 inch x 2 inch x 2 inch by 1 pound item and completed checkout.

I noticed in my local server logs that the correct (smaller) box was used for the rate request...

```
<RateV4Request USERID="150WOOTH2143">
  <Revision>2</Revision>
  <Package ID="Package_0">
    <Service>ALL</Service>
    <ZipOrigination>98290</ZipOrigination>
    <ZipDestination>98290</ZipDestination>
    <Pounds>0</Pounds>
    <Ounces>32</Ounces>
    <Container>VARIABLE</Container>
    <Size>REGULAR</Size>
    <Width>6</Width>
    <Length>6</Length>
    <Height>6</Height>
    <Girth>24</Girth>
    <Machinable>TRUE</Machinable>
  </Package>
</RateV4Request>
```

but we don't surface that information anywhere in Edit Order.

I'm not sure how hard this will be to implement - let's get an estimate before we dig into this one.

**Comment by nabsul** [comment]
The server currently returns packaging information that is ignored by the client. I was thinking we could very simply add metadata the way the Xero plugin does.

More elaborately, I suppose we could add a tab in the view that shows all this information.

**Comment by DanReyLop** [comment]
This is doable in a reasonable amount of time. The order has the needed meta-data, so we would just need to attach our code to a filter somewhere and present this information. Unfortunaly, we can't rely on any core WooCommerce functionality, since its `packages` meta-data support is quite rudimentary.

@kellychoffman Where should we put it? The Edit Order page seems too packed with information already. Also a rough mock-up would be nice to have :)

**Comment by allendav** [comment]
Moving this out of sprint 6 to make room for an urgent server issue

This still needs design

**Comment by robobot3000** [comment]
This was added in #713
