### ISSUE TITLE
[Labels] Packages step UI (readonly) Design

### ISSUE THREAD

**Issue by kellychoffman** [Automattic/woocommerce-connect-client#511]
Design for issue #505 (@nabsul) of the same name.

If, for some reason the weight hasn't been entered, you would see a warning denoted by the gridicon, the color, and the description. If this was the only section with an error, it would be expanded by default. 

![](https://cloud.githubusercontent.com/assets/5835847/17910984/b05604d8-6948-11e6-9e8b-ca616dc075a0.png)

Once the weight has been entered:

![](https://cloud.githubusercontent.com/assets/5835847/17911004/cab1a67a-6948-11e6-9f01-8085971118bc.png)

Header: 

- gridicon `checkmark` or `notice-outline` depending on status
- title: `Packages`
- description: Weight. Example: `Weight: 30.4 lbs`

Note on content: no need to include the 'Weigh using scale' button in this sprint, will revisit this much further down the road. Everything else in the content area should be included. 

Full flow: #501

**Comment by DanReyLop** [comment]
A couple of questions:

Since for this sprint the packages step will be read-only, what should we put instead of the dropdown?

This design doesn't show the list of items in each package. I think this information is important to the merchant.

Since we have `box_weight` and (probably) the `weight` of each item, can we pre-fill the `Weight` field? If so, should the step be marked as a "warning" until the merchant expands it?

If the weight is not entered, should we display the "red cross" instead of the "yellow notice"? We display the "yellow notice" as a warning in the Address steps, but that doesn't require the intervention of the user (you can purchase the label even with a "warning" step).

**Comment by kellychoffman** [comment]
> Since for this sprint the packages step will be read-only, what should we put instead of the dropdown?
> This design doesn't show the list of items in each package. I think this information is important to the merchant.

![screen shot 2016-09-06 at 3 16 28 pm](https://cloud.githubusercontent.com/assets/5835847/18291435/ebbb46ee-7444-11e6-8c59-5f05cc517787.png)

> Since we have box_weight and (probably) the weight of each item, can we pre-fill the Weight field? If so, should the step be marked as a "warning" until the merchant expands it?

If we have the weight, shouldn't we just prefill it and mark it with an ✅ ? The merchant would see the weight in the card header description. 

> If the weight is not entered, should we display the "red cross" instead of the "yellow notice"? We display the "yellow notice" as a warning in the Address steps, but that doesn't require the intervention of the user (you can purchase the label even with a "warning" step).

Yes, if the weight is not entered, it should have the red warning `!`.

**Comment by allendav** [comment]
Will open new issues as needed - this is working well
