### ISSUE TITLE
Replace catch( noop ) with at least console logging in shipping-label/state/actions.js

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-connect-client#556]
In three places (getRates, submitAddressForNormalization and purchaseLabel) we have catch( noop ) which silently consumes exceptions (like what was happening here: https://github.com/Automattic/woocommerce-connect-client/pull/555#issuecomment-247690790 )

I think we should at least be console logging the exception. Otherwise debugging and happiness will have nothing to go on other than "I clicked the (enabled) button and nothing happens"

**Comment by DanReyLop** [comment]
If we remove the `.catch(noop)`, then the default behaviour (at least in Chrome) is to log an error to the console.

Putting there the `catch(noop)` was a conscious decision, because the error is handled by changing the state of the redux tree (at least in `submitAddressForNormalization` and `purchaseLabel`). Also, the promise being rejected doesn't mean that there was a cathastrophic error. In the case of the address normalization, the Promise will be rejected if the address is invalid, which is a perfectly normal code path.

**Comment by allendav** [comment]
> Also, the promise being rejected doesn't mean that there was a cathastrophic error.

Are you sure? Isn't that what happened here? https://github.com/Automattic/woocommerce-connect-client/pull/555#issuecomment-247690790

What do you think about the idea of displaying a user facing error, like I propose here https://github.com/Automattic/woocommerce-connect-client/pull/594#issuecomment-250507245

> In the case of the address normalization, the Promise will be rejected if the address is invalid

Under what circumstances is the address "invalid" - basically always (i.e. Street instead of ST) or only if something major is wrong like the city missing?

**Comment by DanReyLop** [comment]
> Under what circumstances is the address "invalid"

When the address doesn't exist, for example `Fake Street 123, San Francisco, Alabama`.

> Are you sure? Isn't that what happened here? #555 (comment)

Yes, but not always. Sometimes a Promise being rejected just means that the server returned an error, but it's still a normal code path and should be handled by the form UI. I'll give this another try, it's important to show errors but we shouldn't treat all errors equally :)
